# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('crag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Crag')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sector'),
        ),
    ]
