# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_route_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Route')),
            ],
        ),
    ]
