# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20161121_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=20)),
                ('multiplier', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='climbrecord',
            name='style',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='climbstyle',
            unique_together=set([('user', 'style')]),
        ),
    ]
